### ISSUE TITLE
Fix /vampire reload command

### ISSUE THREAD

**Issue by TheMikol** [pixkk/Vampires#4]
After reloading the plugin, arenas do not start
Pufferfish 1.19.3, latest VampireZ (3.1.2.2)

[11:30:16] [Server thread/WARN]: [VampireZ] Task #117493 for VampireZ v3.0.1 generated an exception
java.lang.NoClassDefFoundError: com/tigerhix/vampirez/lib/Metrics$JsonObjectBuilder$JsonObject
	at com.tigerhix.vampirez.lib.Metrics$MetricsBase.submitData(Metrics.java:285) ~[Vampires.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1475) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:450) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1399) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.tigerhix.vampirez.lib.Metrics$JsonObjectBuilder$JsonObject
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 9 more
[11:30:17] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to VampireZ v3.0.1
java.lang.NoClassDefFoundError: com/tigerhix/vampirez/Game$2
	at com.tigerhix.vampirez.Game.ready(Game.java:165) ~[Vampires.jar:?]
	at com.tigerhix.vampirez.Game.join(Game.java:98) ~[Vampires.jar:?]
	at com.tigerhix.vampirez.Sign.onInteract(Sign.java:132) ~[Vampires.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor713.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:git-Pufferfish-61]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:546) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:528) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1960) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1343) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1320) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1313) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1291) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[pufferfish-1.19.3.jar:git-Pufferfish-61]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.tigerhix.vampirez.Game$2
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 29 more

**Comment by pixkk** [comment]
Fixed in https://github.com/pixkk/Vampires/releases/tag/3.2.1 release. (reload command reload only messages file from this version).
